/**
 * The friendly calendar-name index.
 *
 * Google Calendar wants an id; a person wants to say "Study". This maps one to
 * the other and lives at `<userData>/calendars.json`.
 *
 * The path is a parameter rather than something resolved here, so the module has
 * no Electron dependency and is testable against a temporary file.
 *
 * The shape matches the implementation this was ported from, deliberately: the
 * only real change is *where* the file lives. There, it sat under `safe/` and was
 * generated by a script that no longer existed, so the map only ever resolved
 * `"primary"`. Here it is refreshed from `calendar_list_calendars`, which is the
 * one call that makes the whole indirection worth having.
 */

import fs from "node:fs";
import path from "node:path";

export interface CalendarEntry {
  id: string;
  name: string;
  description: string;
  primary: boolean;
  selected: boolean;
  accessRole: string;
  timeZone: string | null;
}

export interface CalendarIndex {
  /** Both the display name and the id map to the id, so either can be passed in. */
  byName: Record<string, string>;
  byId: Record<string, CalendarEntry>;
  list: CalendarEntry[];
  generatedAt: string;
}

export function emptyCalendarIndex(): CalendarIndex {
  return { byName: {}, byId: {}, list: [], generatedAt: "" };
}

function str(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

/**
 * Coerce the payload of `calendar_list_calendars` into entries.
 *
 * Forgiving on purpose: the payload crosses a process boundary as `unknown`, and
 * one malformed entry should cost that entry rather than the whole refresh.
 */
export function coerceCalendarEntries(payload: unknown): CalendarEntry[] {
  const container = payload as { calendars?: unknown } | null | undefined;
  const list: unknown[] = Array.isArray(payload)
    ? payload
    : Array.isArray(container?.calendars)
      ? (container?.calendars as unknown[])
      : [];

  const entries: CalendarEntry[] = [];
  for (const raw of list) {
    if (typeof raw !== "object" || raw === null) continue;
    const item = raw as Record<string, unknown>;
    const id = str(item.id).trim();
    if (!id) continue;
    entries.push({
      id,
      name: str(item.name).trim() || id,
      description: str(item.description),
      primary: item.primary === true,
      selected: item.selected !== false,
      accessRole: str(item.accessRole),
      timeZone: typeof item.timeZone === "string" ? item.timeZone : null,
    });
  }
  return entries;
}

/**
 * Build an index from entries.
 *
 * Both the name and the id are registered as lookup keys, so a config value of
 * either form resolves. The id is registered last and wins, so a calendar whose
 * *name* collides with another calendar's id cannot shadow it.
 */
export function buildCalendarIndex(entries: CalendarEntry[], now: Date): CalendarIndex {
  const byName: Record<string, string> = {};
  const byId: Record<string, CalendarEntry> = {};

  for (const entry of entries) {
    byId[entry.id] = entry;
    if (entry.name) byName[entry.name] = entry.id;
  }
  for (const entry of entries) {
    byName[entry.id] = entry.id;
  }

  return { byName, byId, list: entries, generatedAt: isoOrEmpty(now) };
}

function isoOrEmpty(now: Date): string {
  try {
    return now.toISOString();
  } catch {
    return "";
  }
}

/** Parse a stored index. Returns null rather than throwing on a damaged file. */
export function parseCalendarIndex(raw: string): CalendarIndex | null {
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null) return null;
    const candidate = parsed as Partial<CalendarIndex>;
    if (typeof candidate.byName !== "object" || candidate.byName === null) return null;
    return {
      byName: candidate.byName as Record<string, string>,
      byId: (candidate.byId ?? {}) as Record<string, CalendarEntry>,
      list: Array.isArray(candidate.list) ? (candidate.list as CalendarEntry[]) : [],
      generatedAt: typeof candidate.generatedAt === "string" ? candidate.generatedAt : "",
    };
  } catch {
    return null;
  }
}

/**
 * Read the index from disk.
 *
 * A missing file is the normal state before the first refresh, and a damaged one
 * is recoverable by refreshing — neither is an error worth surfacing, so both
 * return null and the caller falls back to the configured id.
 */
export function readCalendarIndex(file: string): CalendarIndex | null {
  try {
    return parseCalendarIndex(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

/** Write the index atomically, so a crash mid-write cannot leave a half file. */
export function writeCalendarIndex(
  file: string,
  index: CalendarIndex,
): { ok: boolean; error?: string } {
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.tmp`;
    fs.writeFileSync(tmp, `${JSON.stringify(index, null, 2)}\n`, "utf8");
    fs.renameSync(tmp, file);
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

/**
 * Turn whatever the user configured into an id Google will accept.
 *
 * Order: a mapped name, then the value itself, then the fallback. An unmapped
 * value is passed through unchanged rather than rejected, because a raw calendar
 * id is a perfectly good thing to type into Settings.
 */
export function resolveCalendarId(
  index: CalendarIndex | null,
  value: string | null | undefined,
  fallback = "primary",
): string {
  const requested = String(value ?? "").trim();
  if (!requested) return fallback;

  const mapped = index?.byName?.[requested];
  if (typeof mapped === "string" && mapped) return mapped;

  return requested;
}

/** Every name the index can resolve, for a Settings hint. */
export function knownCalendarNames(index: CalendarIndex | null): string[] {
  if (!index) return [];
  return index.list.map((entry) => entry.name).filter(Boolean);
}
